### ISSUE TITLE
NullPointerException with the runner client interface

### ISSUE THREAD

**Issue by vosscodes** [jenkinsci/saltstack-plugin#143]
On version 3.2.2, when using the `runner` client and specifying a function with `pillarvalue` unset, a null pointer exception occurs. We're using this with `saltutil.sync_all`, but it can be easily reproduced with:

```
pipeline {
    agent any
    stages {
        stage('sync') {
            steps {
                salt(
                    servername: 'https://ip:8000',
                    credentialsId: 'credential-id',
                    authtype: 'pam',
                    saveFile: true,
                    clientInterface: runner(function: 'test.get_opts')
                )
            }
        }
    }
}
```

results in:
```
java.lang.NullPointerException
	at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
	at java.util.regex.Matcher.reset(Matcher.java:309)
	at java.util.regex.Matcher.<init>(Matcher.java:229)
	at java.util.regex.Pattern.matcher(Pattern.java:1093)
	at com.waytta.Utils.paramorize(Utils.java:41)
	at com.waytta.SaltAPIBuilder.prepareSaltFunction(SaltAPIBuilder.java:412)
	at com.waytta.SaltAPIStep$Execution.prepareRun(SaltAPIStep.java:336)
	at com.waytta.SaltAPIStep$Execution.start(SaltAPIStep.java:257)
```

full stack trace: https://gist.github.com/vosscodes/a67bab3a4d1a0fb5132485cf961b5b6c

The same works with the simple addition of `, pillarvalue: ''` after `function`

**Comment by mchugh19** [comment]
Thanks for the report. This has just been corrected, and will be released as 3.2.3.
