### ISSUE TITLE
test=True kwarg fails to return output to build console log

### ISSUE THREAD

**Issue by tyhunt99** [jenkinsci/saltstack-plugin#17]
I am trying to use the kwarg test=True to see the changes before I actually run them but it fails to return any output in the build logs. It gives the following error:

```
Started by user Tyler Hunt
[EnvInject] - Loading node environment variables.
Building in workspace /usr/share/tomcat7/.jenkins/jobs/A Salt the Server/workspace
ERROR: Build step failed with exception
net.sf.json.JSONException: JSONObject["result"] is not a Boolean.
	at net.sf.json.JSONObject.getBoolean(JSONObject.java:1929)
	at com.waytta.Utils.validateInnerJsonObject(Utils.java:208)
	at com.waytta.Utils.validateInnerJsonObject(Utils.java:215)
	at com.waytta.Utils.validateFunctionCall(Utils.java:178)
	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:377)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Send a message to Salt API' marked build as failure
Notifying upstream projects of job completion
Finished: FAILURE
```

When I run it without specifying test=True then it works. It also works with any other arguments or kwargs. I tested with the following equivalent salt commands (translated from build params to what is passed into salt):

```
salt '*' test.arg 1 "two" 3.1
salt '*' test.arg txt="hello" wow='{a: 1, b: "hello"}'
salt '*' test.arg 1 "two" 3.1 txt="hello" wow='{a: 1, b: "hello"}'
```

These worked just fine. Some more tests resulted in interesting findings:
```
salt '*' state.sls docker mock=True test=True #worked fine
salt '*' state.sls docker test=True #resulted in the error
```

**Comment by mchugh19** [comment]
Interesting! Thanks for the feedback. 

From the error, it sounds like the saltapi is returning a result key, but one that its value is not boolean. 

I've attempted to replicate by running state.sls on a vim install state, but adding test=True seems to work just fine. 

![image](https://cloud.githubusercontent.com/assets/1360357/13973001/36d706d4-f06c-11e5-88ea-acf4deeaca3e.png)


I suppose that it is possible that your docker state is returning something unexpected. Could you please send me the json returned by the saltapi? [Here](https://gist.github.com/mchugh19/b7a5084c3a5395bf03ac) is a sample curl that you can use to test.

**Comment by mchugh19** [comment]
To make this process a bit easier, I've just added printing the saltapi response when you have jenkins salt plugin's debug box checked.

https://github.com/jenkinsci/saltstack-plugin/releases/tag/1.7.1-beta1

Can you please try to replicate once more with that release and send the console output? 

Thanks!

**Comment by mchugh19** [comment]
This was likely just fixed as reported in [jira](https://issues.jenkins-ci.org/browse/JENKINS-34535)

Seems that the salt-api returns result: null when running a state.highstate test=True, but only when there are changes to be performed.
