### ISSUE TITLE
Plugin fails with NPE when configured with a nonexistant variable

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#19]
When there is a variable such as {{BADVARIABLE}} in configuration, that doesn't exist in the environment, the plugin fails with NPE:

```
ERROR: Build step failed with exception
java.lang.NullPointerException
	at java.lang.String.replace(String.java:2240)
	at com.waytta.Utils.paramorize(Utils.java:125)
	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:222)
	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:782)
	at hudson.model.Build$BuildExecution.build(Build.java:205)
	at hudson.model.Build$BuildExecution.doRun(Build.java:162)
	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
	at hudson.model.Run.execute(Run.java:1738)
	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
	at hudson.model.ResourceController.execute(ResourceController.java:98)
	at hudson.model.Executor.run(Executor.java:410)
Build step 'Send a message to Salt API' marked build as failure
```
This would be great if I could get a notification which variable failed to resolve. 'Cos this got me wondering what happened to the job and then took me some time to figure out which variable was mispelled and causing the error (i have several variables in the plugin config (salt role, pillar parameters, etc)

**Comment by zerthimon** [comment]
Or, even better, log a warning and resolve to an empty string

**Comment by mchugh19** [comment]
Thanks for the report! Now avoiding the NPE as of 92e0da4
