### ISSUE TITLE
local batch broken ?

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#79]
Same configuration, works for "local" but doesn't for "local batch".
```
17:02:52 Running in batch mode. Batch size: 1
17:02:52 ERROR: Build step failed with exception
17:02:52 net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.
17:02:52 	at net.sf.json.JSONObject.getJSONArray(JSONObject.java:1986)
17:02:52 	at com.waytta.SaltAPIBuilder.performRequest(SaltAPIBuilder.java:268)
17:02:52 	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:204)
17:02:52 	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:164)
17:02:52 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
17:02:52 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
17:02:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
17:02:52 	at hudson.model.Build$BuildExecution.build(Build.java:206)
17:02:52 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
17:02:52 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
17:02:52 	at hudson.model.Run.execute(Run.java:1730)
17:02:52 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
17:02:52 	at hudson.model.ResourceController.execute(ResourceController.java:97)
17:02:52 	at hudson.model.Executor.run(Executor.java:405)
17:02:52 Build step 'Send a message to Salt API' marked build as failure
```

**Comment by zerthimon** [comment]
Hmmm, is this related to this: https://github.com/jenkinsci/saltstack-plugin/issues/58 ?

**Comment by zerthimon** [comment]
Yeah, well done, saltstack!
Closing

**Comment by mchugh19** [comment]
`local_batch` will hopefully return soon saltstack/salt#40598

**Comment by zerthimon** [comment]
@mchugh19 so batch support was backported to 2016.11.4 but I'm getting some weird problems while running batch jobs via API. Do you know if anything should be added to eauth config to make it work ?
