### ISSUE TITLE
JSONException is not really informative

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#81]
I've been getting these errors when job is fails to run due to an error in targeting for example.
Probably every time that API replies with error.
Printing the error instead of this Exception would be more informative to the user.
```
08:46:13 ERROR: Build step failed with exception
08:46:13 net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.
08:46:13 	at net.sf.json.JSONObject.getJSONArray(JSONObject.java:1986)
08:46:13 	at com.waytta.SaltAPIBuilder.performRequest(SaltAPIBuilder.java:268)
08:46:13 	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:204)
08:46:13 	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:164)
08:46:13 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
08:46:13 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
08:46:13 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
08:46:13 	at hudson.model.Build$BuildExecution.build(Build.java:206)
08:46:13 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
08:46:13 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
08:46:13 	at hudson.model.Run.execute(Run.java:1730)
08:46:13 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
08:46:13 	at hudson.model.ResourceController.execute(ResourceController.java:97)
08:46:13 	at hudson.model.Executor.run(Executor.java:405)
08:46:13 Build step 'Send a message to Salt API' marked build as failure
08:46:13 Notifying upstream projects of job completion
08:46:13 Finished: FAILURE
```

**Comment by mchugh19** [comment]
This has been corrected in the master branch (as of #72 ) and will be in the next release.

**Comment by zerthimon** [comment]
Coolio. Closing.

**Comment by mchugh19** [comment]
Version 3.0 released which incorporates these fixes. The major version was bumped due to supporting saltapi with tornado, which caused changes to the returned output for both tornado and cherrypy. 

Pre-3.0 output
```
"return": [{
  "minionid": "Results and output"
}]
```

Output in 3.0
```
"Result": {
  "minionid": {
    "return": "Results and output"
  }
}
```
