### ISSUE TITLE
long living job timeouts with exception when running through local batch interface

### ISSUE THREAD

**Issue by zerthimon** [jenkinsci/saltstack-plugin#82]
I have a very long deploy job that I have to run with bacth = 1 to deploy servers one by one.
The job fails with this famous exception:
```
12:05:37 Running in batch mode. Batch size: 1
12:12:42 ERROR: Build step failed with exception
12:12:42 net.sf.json.JSONException: JSONObject["return"] is not a JSONArray.
12:12:42 	at net.sf.json.JSONObject.getJSONArray(JSONObject.java:1986)
12:12:42 	at com.waytta.SaltAPIBuilder.performRequest(SaltAPIBuilder.java:268)
12:12:42 	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:204)
12:12:42 	at com.waytta.SaltAPIBuilder.perform(SaltAPIBuilder.java:164)
12:12:42 	at hudson.tasks.BuildStepCompatibilityLayer.perform(BuildStepCompatibilityLayer.java:81)
12:12:42 	at hudson.tasks.BuildStepMonitor$1.perform(BuildStepMonitor.java:20)
12:12:42 	at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:779)
12:12:42 	at hudson.model.Build$BuildExecution.build(Build.java:206)
12:12:42 	at hudson.model.Build$BuildExecution.doRun(Build.java:163)
12:12:42 	at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
12:12:42 	at hudson.model.Run.execute(Run.java:1730)
12:12:42 	at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
12:12:42 	at hudson.model.ResourceController.execute(ResourceController.java:97)
12:12:42 	at hudson.model.Executor.run(Executor.java:405)
12:12:42 Build step 'Send a message to Salt API' marked build as failure
12:12:43 Notifying upstream projects of job completion
12:12:43 Finished: FAILURE
```
And in the api log:
```
2017-04-13 12:12:42,797 [cherrypy.error   ][ERROR   ][24988] [13/Apr/2017:12:12:42]  Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 169, in trap
    return func(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 96, in __call__
    return self.nextapp(environ, start_response)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 379, in tail
    return self.response_class(environ, start_response, self.cpapp)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 222, in __init__
    self.run()
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cpwsgi.py", line 320, in run
    request.run(meth, path, qs, rproto, headers, rfile)
  File "/usr/lib/python2.7/dist-packages/cherrypy/_cprequest.py", line 603, in run
    raise cherrypy.TimeoutError()
TimeoutError
```
So in local interface we have polling with ￼'Wait for completion' and 'Poll Time' options.
Is setting `expire_responses: False` my only option to fix this ?

**Comment by mchugh19** [comment]
It appears that it is it the saltapi that is timing this out. If that's the case, then you are correct and the `expire_responses: False` is the setting to work around this. I don't see any other setting in the salt cherrypy documentation for changing the timeout time, but you might want to ask in the salt mailing list.

**Comment by zerthimon** [comment]
Thanks @mchugh19 ! Closing..
